package com.ecervera.cocktails.testshared

import com.ecervera.cocktails.domain.Drink

val sampleDrink = Drink(
    idDrink = "0",
    "Alcoholic",
    "Cocktail",
    "No",
    "Gin Tonic",
    "http://localhost/images/drink/test_thumb",
    "ighball glass",
    "http://localhost/images/drink/test_image_source",
    "Gin",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    instructions = "Description test",
    measure1 = "1 ml",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    tags = "best",
    video = "http://localhost/images/drink/test_video",
    isFavorite = false,
)